version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./task_manager.db
    volumes:
      - ./task_manager.db:/app/task_manager.db